name: Full Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Generate JaCoCo report
        run: |
          mkdir -p jacocoSrc/it/czerwinski/home/
          ln -s `pwd`/src/main/kotlin jacocoSrc/it/czerwinski/home/monitoring
          ./gradlew jacocoTestReport
      - name: Archive JAR artifacts
        uses: actions/upload-artifact@v1
        with:
          name: libs
          path: build/libs
      - name: Archive JaCoCo report
        uses: actions/upload-artifact@v1
        with:
          name: jacoco
          path: build/reports/jacoco
